
openapi: 3.0.0
info:
  title: Sample Pet Store API
  description: A sample API that uses a petstore as an example
  version: 1.0.0
paths:
  /pets:
    get:
      summary: List all pets
      responses:
        '200':
          description: A list of pets.
    post:
      summary: Create a pet
      responses:
        '201':
          description: Pet created
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet
          schema:
            type: string
      responses:
        '200':
          description: Pet details
